# GrievX K-Means Clustering Project

In [1]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.cluster import KMeans

from sklearn.pipeline import Pipeline

import joblib

In [3]:
df = pd.read_csv(
    "expanded_historical_complaints_dataset.csv"
)

df.head()

,Problem_Name,Problem_Category,Ministry,Minister_Name,Days_To_Complete
0,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4
1,Government housing delay,housing,minister for housing and urban development,S Muthusamy,10
2,Government housing delay,housing,minister for housing and urban development,S Muthusamy,6
3,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4
4,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4

In [4]:
X = df["Problem_Name"]

In [5]:
model = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('kmeans', KMeans(
        n_clusters=5,
        random_state=0
    ))
])

In [6]:
model.fit(X)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('kmeans', KMeans(n_clusters=5, random_state=0))])

In [7]:
clusters = model.predict(X)

print(clusters)

[0 0 0 ... 2 2 2]

In [8]:
df["Cluster"] = clusters

df.head()

,Problem_Name,Problem_Category,Ministry,Minister_Name,Days_To_Complete,Cluster
0,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4,0
1,Government housing delay,housing,minister for housing and urban development,S Muthusamy,10,0
2,Government housing delay,housing,minister for housing and urban development,S Muthusamy,6,0
3,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4,0
4,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4,0

In [9]:
prediction = model.predict([
    "Poor bus service"
])

print(
    "Cluster :",
    prediction[0]
)

Cluster : 2

In [10]:
prediction = model.predict([
    "Water leakage issue"
])

print(
    "Cluster :",
    prediction[0]
)

Cluster : 1

In [11]:
prediction = model.predict([
    "Hospital cleanliness complaint"
])

print(
    "Cluster :",
    prediction[0]
)

Cluster : 4

In [12]:
joblib.dump(
    model,
    "grievx_kmeans_model.joblib"
)

print("Model Saved Successfully")

Model Saved Successfully

In [13]:
import os

os.listdir()

['.config',
 'tamilnadu_2021_ministers_dataset.csv',
 'grievx_kmeans_model.joblib',
 'expanded_historical_complaints_dataset.csv',
 'Final_MLA + Ward member_Dataset _.csv',
 'sample_data']