# One Hot Encoding - Complaint Prediction Project

In [1]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from google.colab import files

In [2]:
uploaded = files.upload()

Saving expanded_historical_complaints_dataset.csv to expanded_historical_complaints_dataset.csv

In [3]:
df = pd.read_csv("expanded_historical_complaints_dataset.csv")

df.head()

,Problem_Name,Problem_Category,Ministry,Minister_Name,Days_To_Complete
0,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4
1,Government housing delay,housing,minister for housing and urban development,S Muthusamy,10
2,Government housing delay,housing,minister for housing and urban development,S Muthusamy,6
3,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4
4,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4

In [4]:
X = df[[
    "Problem_Name",
    "Problem_Category",
    "Ministry",
    "Minister_Name"
]]

X.head()

,Problem_Name,Problem_Category,Ministry,Minister_Name
0,Government housing delay,housing,minister for housing and urban development,S Muthusamy
1,Government housing delay,housing,minister for housing and urban development,S Muthusamy
2,Government housing delay,housing,minister for housing and urban development,S Muthusamy
3,Government housing delay,housing,minister for housing and urban development,S Muthusamy
4,Government housing delay,housing,minister for housing and urban development,S Muthusamy

In [5]:
ct = ColumnTransformer(
    transformers=[
        (
            "encoder",
            OneHotEncoder(),
            [
                "Problem_Name",
                "Problem_Category",
                "Ministry",
                "Minister_Name"
            ]
        )
    ],
    remainder="passthrough"
)

In [6]:
X = ct.fit_transform(X)

In [7]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 140260 stored elements and shape (35065, 120)>
  Coords	Values
  (0, 20)	1.0
  (0, 81)	1.0
  (0, 95)	1.0
  (0, 114)	1.0
  (1, 20)	1.0
  (1, 81)	1.0
  (1, 95)	1.0
  (1, 114)	1.0
  (2, 20)	1.0
  (2, 81)	1.0
  (2, 95)	1.0
  (2, 114)	1.0
  (3, 20)	1.0
  (3, 81)	1.0
  (3, 95)	1.0
  (3, 114)	1.0
  (4, 20)	1.0
  (4, 81)	1.0
  (4, 95)	1.0
  (4, 114)	1.0
  (5, 20)	1.0
  (5, 81)	1.0
  (5, 95)	1.0
  (5, 114)	1.0
  (6, 20)	1.0
  :	:
  (35058, 119)	1.0
  (35059, 18)	1.0
  (35059, 77)	1.0
  (35059, 91)	1.0
  (35059, 119)	1.0
  (35060, 18)	1.0
  (35060, 77)	1.0
  (35060, 91)	1.0
  (35060, 119)	1.0
  (35061, 18)	1.0
  (35061, 77)	1.0
  (35061, 91)	1.0
  (35061, 119)	1.0
  (35062, 18)	1.0
  (35062, 77)	1.0
  (35062, 91)	1.0
  (35062, 119)	1.0
  (35063, 18)	1.0
  (35063, 77)	1.0
  (35063, 91)	1.0
  (35063, 119)	1.0
  (35064, 18)	1.0
  (35064, 77)	1.0
  (35064, 91)	1.0
  (35064, 119)	1.0

In [8]:
print(X.shape)

(35065, 120)