# GrievX Logistic Regression Multiclass

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.linear_model import LogisticRegression

from sklearn.pipeline import Pipeline

import joblib

from google.colab import files

In [2]:
df = pd.read_csv(
    "expanded_historical_complaints_dataset.csv"
)

df.head()

,Problem_Name,Problem_Category,Ministry,Minister_Name,Days_To_Complete
0,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4
1,Government housing delay,housing,minister for housing and urban development,S Muthusamy,10
2,Government housing delay,housing,minister for housing and urban development,S Muthusamy,6
3,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4
4,Government housing delay,housing,minister for housing and urban development,S Muthusamy,4

In [3]:
X = df["Problem_Name"]

y = df["Days_To_Complete"]

In [4]:
def convert_days(days):

    if days <= 3:
        return "Fast"

    elif days <= 7:
        return "Medium"

    else:
        return "Slow"

In [5]:
y = y.apply(convert_days)

y.head()

0    Medium
1      Slow
2    Medium
3    Medium
4    Medium
Name: Days_To_Complete, dtype: object

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=0
)

In [7]:
model = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', LogisticRegression(
        multi_class='multinomial',
        max_iter=1000
    ))
])

In [8]:
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classifier',
                 LogisticRegression(max_iter=1000, multi_class='multinomial'))])

In [9]:
y_pred = model.predict(X_test)

print(y_pred)

['Slow' 'Slow' 'Slow' ... 'Slow' 'Slow' 'Slow']

In [10]:
score = model.score(X_test, y_test)

print("Accuracy :", score)

Accuracy : 0.8243262512476829

In [11]:
prediction = model.predict([
    "Poor bus service"
])

print(
    "Predicted Complaint Speed :",
    prediction[0]
)

Predicted Complaint Speed : Slow

In [12]:
prediction = model.predict([
    "Hospital cleanliness complaint"
])

print(
    "Predicted Complaint Speed :",
    prediction[0]
)

Predicted Complaint Speed : Slow

In [13]:
prediction = model.predict([
    "Water leakage issue"
])

print(
    "Predicted Complaint Speed :",
    prediction[0]
)

Predicted Complaint Speed : Slow

In [14]:
joblib.dump(
    model,
    "grievx_logistic_multiclass_model.joblib"
)

print("Model Saved Successfully")

Model Saved Successfully

In [15]:
import os

os.listdir()

['.config',
 'expanded_historical_complaints_dataset.csv',
 'grievx_logistic_multiclass_model.joblib',
 'sample_data']

In [16]:
files.download(
    "grievx_logistic_multiclass_model.joblib"
)